version: '3.3'

services:
  db:
    container_name: 'node-mysql'
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'node_demo'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./docker/db:/var/lib/mysql
